# Generated by Django 6.0.6 on 2026-06-27 15:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('file', models.FileField(upload_to='documents/')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('extraction_timestamp', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'indexes': [models.Index(fields=['status'], name='contracts_d_status_2eeb64_idx')],
            },
        ),
        migrations.CreateModel(
            name='ExtractedClause',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clause_text', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clauses', to='contracts.document')),
            ],
        ),
        migrations.CreateModel(
            name='RiskFlag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('risk_type', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('clause', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='risk_flags', to='contracts.extractedclause')),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='risk_flags', to='contracts.document')),
            ],
        ),
        migrations.AddIndex(
            model_name='extractedclause',
            index=models.Index(fields=['document'], name='contracts_e_documen_342761_idx'),
        ),
        migrations.AddConstraint(
            model_name='riskflag',
            constraint=models.UniqueConstraint(fields=('document', 'clause', 'risk_type'), name='unique_risk_flag'),
        ),
    ]
